name: Release to Maven Central

on:
  workflow_dispatch: # manual deploy

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: |
          ./gradlew clean build publish --no-daemon \
            -PossrhUsername=${{ secrets.OSSRH_USERNAME }} \
            -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} \
            -Psigning.keyId=${{ secrets.GPG_KEY_ID }} \
            -Psigning.password=${{ secrets.GPG_PASSPHRASE }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}